### ISSUE TITLE
Wallet should be able to be constructed with just a public key and classicAddress or just the classicAddress.

### ISSUE THREAD

**Issue by polar** [XRPLF/xrpl.js#1805]
The current version of Wallet effectively requires its construction from a _private_ key. It appears from the existence of `Wallet#verifyTransaction` that this method is intended merely to be used externally. It is not used internally to the API. It is is only used in tests. Therefore, a Wallet should be able to be constructed solely with a _public_ key and its corresponding _Classic Address_. This approach would make the use of the Wallet more consistent with public key conventions, especially in situations where the API is used to build systems where the private key is not available for obvious reasons. 

The current API does allow for the Wallet to be constructed with arbitrary strings for the public and private keys along with the classic address. It does so without consequence, since `Wallet#verifyTransaction` is not used within the API. Thereby we can currently get around this issue by assigning the `classicAddress` in the constructor options and assign bogus strings to the public and private keys, understanding `Wallet#signTransaction` would not work where the `private_key` is bogus, and `Wallet#verifyTransaction` would not work where the `public_key` is bogus. However, this current approach seems awkward and not very intuitive. Therefore, it would be beneficial to be able to query the Wallet to see if it has a public key, private key, and/or address, or similarly by its generic capabilities:
1. Reference (classicAddress)
2. Verifying (public_key)
3. Signing (private_key)

Also, this situation begs the question of the association of public keys and classic addresses. I suppose that information may be obtained from the ledger, since the public key for the account or the signers is supplied in the transaction. You may query the ledger for any transaction from an account, although that may prove difficult in practice.

**Comment by JST5000** [comment]
As far as I understand it, Wallet was just intended to make it easier to use private keys in whatever format you have them. `Wallet.verifyTransaction` is simply there to make it more convenient to access `verify` from `ripple-keypairs` for a Wallet you're using to sign transactions. 

If you just want to verify a transaction with only the public key, you can do that with 
```
import { verify } from 'ripple-keypairs'
verify(messageHex, txSignature, publicKey)
```

Towards your second question about howpublic keys and classic addresses are associated, the classic address of an account is derived from the corresponding master public key. (More details here: https://xrpl.org/accounts.html#addresses) 
(If you want to derive an address from a master public key, `deriveAddress` from `ripple-keypairs` does that for you)

So, the Wallet class does not need a `classicAddress` to be passed in for the master keypair (it just derives it). The reason Wallet allows including a `classicAddress` explicitly is because someone might set a [regular key](https://xrpl.org/assign-a-regular-key-pair.html#assign-a-regular-key-pair) which does not have any way to derive the `classicAddress` from it's public key. 

Do these two methods let you do what you wanted to do? (Or is there something I'm missing which still requires a Wallet object without a private key?)

**Comment by polar** [comment]
> Or is there something I'm missing which still requires a Wallet object without a private key?

Think about using the Wallet object as a building block in an application or greater library. Of course, you can reference an account now using the Wallet and using the constructions I outlined above, but it is non-intuitive and clunky. 

For instance, in one of my projects I have to extend the wallet object to get what I need.
```
import {Wallet as XrplWallet} from "xrpl";
export class ReferenceWallet extends XrplWallet {
    constructor(masterAddress: string) {
        super("bogus", "bogus", {masterAddress: masterAddress})
    }
}
```
And further I have to create another WalletFactory to wrap the wallet so that I may query the verification and signing capabilities:
```
export class Wallet extends XrplWallet {

    constructor(wallet: XrplWallet) {
        super(wallet.publicKey, wallet.privateKey, {masterAddress: wallet.classicAddress});
    }

    isVerifying(): boolean {
        return this.publicKey != "bogus"
    }

    isSigning(): boolean {
        return this.privateKey != "bogus"
    }
}

export class WalletFactory {
    static generate(algorithm?: ECDSA): Wallet {
        return new Wallet(XrplWallet.generate(algorithm))
    }
    ...
}
```

**Comment by JST5000** [comment]
I see the value in the publicKey "Validation Wallet" which just makes it easy to keep track of the `classicAddress` and `publicKey` and do validations.

For the Reference Wallet case I'm not quite seeing the value of just having a `classicAddress` in a Wallet class because none of the Wallet class functions would be useable. So for that case it seems like it might be better to pass around the `classicAddress` directly. 
(Or does the `classicAddress` need to be wrapped in a Wallet to be used with another function later on?)

**Comment by polar** [comment]
Think of ease of use. If we take the approach to just pass around the classicAddress directly when there is not a private/public key and a Wallet otherwise, then you need complicated approaches involving type safe signatures. For example:
```
function get_lines(account: Wallet | string) {
    if (account instanceof Wallet) {
        return this.api.request({command: "account_lines", account: (account as Wallet).address)
    } else {
        return this.api.request({command: "account_lines, account: (account as string))
    }
}
```
instead of simply:
```
function get_lines(account: Wallet) {
    return this.api.request({command: "account_lines", account: account.address})
}
```
Now add `peer` to that function:

```
function get_lines_for_peer(account: Wallet, peer: Wallet) {
    return this.api.request({command: "account_lines", account: account.address, peer: peer.address})
}
```
and infer how complicated it becomes.

**Comment by JST5000** [comment]
We've decided not to work on this currently. 

If you'd like to submit a PR with your proposal we'll review it, but I think for now having a helper function like the following is a fine (albeit cumbersome since it only applies to one field at a time) workaround:
```
ensureAddress(wallet: Wallet | string): string {
  return wallet?.address ?? wallet
}
```
