### ISSUE TITLE
Integrate base-x into this library directly @ripple-address-codec

### ISSUE THREAD

**Issue by khancode** [XRPLF/xrpl.js#1810]
We should consider dropping the dependency on base-x (an external library), and doing base58 encoding ourselves.

Original issue: https://github.com/ripple/ripple-address-codec/issues/32

**Comment by ckniffen** [comment]
We could use `base64-js` which is used by `buffer` an existing dependency.  This will remove about 1kb.

Another library to look at is `@scur/base` as part of #2273 since we will already be using `@scur/*` for other aspects.  While it is larger as a whole it might be smaller if we only import the base58 method.

**Comment by ckniffen** [comment]
Actually using the latest base-x will work too.  It is pretty small.

**Comment by ckniffen** [comment]
`@scure/base` has built in xrpl alphabet support so going to close this as it will be done in 3.0
