### ISSUE TITLE
Generating an xrp wallet

### ISSUE THREAD

**Issue by MyTestPerson** [XRPLF/xrpl.js#1831]
I studied your documentation earlier, it was very clear. But now, you have very bad documentation.

I spent the whole day trying to find how to generate an XRP wallet, but I couldn't find it.

Can someone tell me?

This doesn't work - new xrpl.Wallet() - https://xrpl.org/get-started-using-javascript.html#3-generate-wallet

const xrpl = require("xrpl")
const test_wallet = new xrpl.Wallet()
console.log(test_wallet)

**Comment by trueIoV** [comment]
Perhaps this will help:

https://js.xrpl.org/classes/Wallet.html#generate

**Comment by trueIoV** [comment]
let wallet = xrpl.Wallet.generate("ECDSA");

work for me.

**Comment by mvadari** [comment]
Yes, it should work with `xrpl.Wallet.generate`. Looks like there was a mistake in the docs; it should be fixed soon.

**Comment by cujo30227** [comment]
Hello,
Also the migration guide gives wrong guidance --> xrpl.generateXAddress() doesn't exists, as well as xrpl.generateAddress(). See https://xrpl.org/xrpljs2-migration-guide.html#validated-results 
I must say that migrating from ripple-lib to xrpl is not straightforward at all, especially since the documentation is not accurate and thus much trail&error is needed to see how the code actually responses...

**Comment by cujo30227** [comment]
Same for xrpl.deriveAddress(), xrpl.deriveKeypair() etc, all not working although the migration guide is specifically mentioning them https://xrpl.org/xrpljs2-migration-guide.html

**Comment by JST5000** [comment]
> Same for xrpl.deriveAddress(), xrpl.deriveKeypair() etc, all not working although the migration guide is specifically mentioning them https://xrpl.org/xrpljs2-migration-guide.html

Thanks for pointing this out! @mDuo13 an issue for `deriveAddress` being missing here: https://github.com/XRPLF/xrpl.js/issues/1871
