### ISSUE TITLE
Unable to get AccountDelete transaction to work

### ISSUE THREAD

**Issue by EddieE79** [XRPLF/xrpl.js#1870]
I'm trying to submit an  "AccountDelete" transaction but am unable to get it to submit to the ledger. 
I have tried using "wss://xrplcluster.com", "wss://s1.ripple.com/", "wss://s2.ripple.com/" for my connection. I just can't get any ledger to accept the transaction.

My transaction details after autofill look like this:
```
{
  TransactionType: 'AccountDelete',
  Account: 'my_account_address',
  Destination: 'my_destination_address',
  Fee: '7000000',
  Flags: 2147483648,
  Sequence: my_sequence_number,
  LastLedgerSequence: my_last_ledger_sequence
}
```

When I submit the transaction I get the following response with these details:
```
{
     ...some stuff
     engine_result: 'telCAN_NOT_QUEUE',
     engine_result_code: -392,
     engine_result_message: 'Can not queue at this time.',
    ... more stuff
    open_ledger_cost: '1051937500',
   ... even more stuff
}
```

I have tried uping the fee all the way to '8000000' (8 XRP)  ~ if the fee is higher than this it nearly(or completely) defeats the point of deleting an account anyway, you may aswell just abandon it.

So I have 3 questions
1) wss://xrplcluster.com site says it filters out any transaction where the fee is greater than 2 XRP ~ Does this mean it will never accept an "AccountDelete" transaction?
2) Is there anyway to find out the fee required submit an AccountDelete transaction to a ledger? Documentation says 2 XRP, xumm.community says it may now take up to 4 ~ Is it the value of the "open_ledger_cost" attribute in my response?
3) Has anyone got an 'AccountDelete' transaction working on a public legder? If so, what fees are you setting?

Any other suggestions/pointers welcome

**Comment by cujo30227** [comment]
FYI : I have the same problem with the old Ripple-Lib. Everything worked fine until a few weeks back. No changes were made on our end ..

**Comment by mvadari** [comment]
This is not a library issue - this is a ledger issue. This error is occurring because a lot of people are submitting transactions (not just you), and the ledger is under a lot of load in general. The `telCAN_NOT_QUEUE` error is occurring because of this load. 

The only thing that will really get the transaction to succeed is a higher fee. The ledger will hopefully return back to normal soon (some fixes are in the pipeline), at which point you should be able to delete your account as normal.

**Comment by EddieE79** [comment]
Is there a way to work out what the fee would be for AccountDelete?  I've tried the "fees" request (documented [here](https://xrpl.org/fee.html) ) but that doesn't give an indication of the fees for AccountDelete

**Comment by JST5000** [comment]
@EddieE79 Unfortunately for AccountDelete transactions, queue priority is determined by [fee levels](https://xrpl.org/transaction-cost.html#fee-levels). Since the base fee for AccountDelete is 2 XRP, a fee of 4 XRP would be an equivalent fee level to a normal transaction paying `20 drops`. One thing that might be worth trying is to use a fee which is just above baseline, such as `2.01` XRP because that will give you priority over transactions which are trying to pay the base fee.

**Comment by EddieE79** [comment]
Closing - this is just a constraint with the ledger at this time, it's not an issue with this library. Thanks everyone for your advice.
