### ISSUE TITLE
convert currency codes

### ISSUE THREAD

**Issue by lathanbritz** [XRPLF/xrpl.js#1886]
Currency codes are parsed as Hex in all ledger objects.

Would be great to have a standard helper function to convert the hex value to the human readable string value.

**Comment by ocean-drop** [comment]
There is the `xrpl.convertHexToString` function. Taking the [SOLO](https://xrpscan.com/account/rsoLo2S1kiGeCcn6hCUXVrCpGMWLrRrLZz) currency which is represented by the following hexadecimal string `534F4C4F00000000000000000000000000000000` 

```JavaScript
let currency = xrpl
.convertHexToString('534F4C4F00000000000000000000000000000000') // returns "SOLO\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
.replaceAll('\u0000', ''); //Removes the Unicode NULL char \u0000

console.log(currency); // -> "SOLO"
```

**Comment by mDuo13** [comment]
Be careful with doing that because with the example above it's possible to make a currency code that decodes to "XRP" but isn't actually XRP.

Here's a more thorough parser:

https://github.com/nixer89/xrpl-services-frontend/blob/7618cde512280bca0421f58d54a952ae13d16954/src/app/utils/normalizers.ts#L111
