### ISSUE TITLE
BroadcastClient doesn't work with events

### ISSUE THREAD

**Issue by Realetive** [XRPLF/xrpl.js#1925]
```typescript
import { BroadcastClient } from 'xrpl'
const client = new BroadcastClient( [ 'wss://xrplcluster.com', 'wss://s2.ripple.com' ] )

client.on( 'connected', async () => {
  console.log( `connected` )
} )

await client.connect()
```

We have never get `connected`.

But if we replace `BroadcastClient` to `Client` it's ok.

**Comment by mvadari** [comment]
The broadcast client is still experimental. It appears that we forgot to label it as so.

**Comment by intelliot** [comment]
@Realetive what's your use case for BroadcastClient? 

I don't think it's actually useful in practice. It will most likely be deleted.

**Comment by intelliot** [comment]
Unfortunately, the current implementation of BroadcastClient doesn't succeed in providing better reliability in practice. A better approach is to use one endpoint and implement reconnect / error handling on the client side. Redundancy and high availability should be provided on the server side. This is the approach used by most internet services (which is why you can always go to google.com, instead of checking google1.example.com, google2.example.com, ...)

There is a rippled WebSocket proxy implementation (providing load balancing and redundancy) here: https://github.com/XRPLF/xrpl.ws-Edge-Proxy

**Comment by mvadari** [comment]
[xrpl-client](https://github.com/XRPL-Labs/xrpl-client/) also might be what you're looking for

**Comment by khancode** [comment]
Closing since we've deprecated BroadcastClient
