### ISSUE TITLE
Retrieve NFT tokenId

### ISSUE THREAD

**Issue by andrew-keig-noumena** [XRPLF/xrpl.js#1945]
Question, possible enhancement.

Say for example I have minted a token and I decide to burn a token, we are storing the transactionId, as this is the only identifier I can use to view this token on the xrpl explorer.  I perform a get transaction and get back a txResponse, in order to get the tokenId, I need to perform something like the following:

```
export const getXrplTokenId = (tx: unkown): string => {
  const node = tx?.result?.meta?.AffectedNodes?.find((x: unknown) => x.ModifiedNode?.FinalFields?.NonFungibleTokens)
  const token = node?.ModifiedNode?.FinalFields?.NonFungibleTokens?.find(
    (t) => t.NonFungibleToken?.URI === tx?.result?.URI,
  )
  return token?.NonFungibleToken?.TokenID || ""
}

```

1. Is there a better way of doing this?
2. Why do we return all NFTs for an account? Could we simply return the tokenId related to the transaction.

Thanks in advance..

**Comment by ledhed2222** [comment]
I am working currently on allowing the explorer to query tokens by tokenid, including previously-burnt tokens.

Unfortunately, this is not a simple task due to the way that NFTs are stored. NFTs are stored in the way that they are, despite this complexity, as a performance measure; it decreases ledger size and decreases a user's XRP reserve needed per NFT owned.

1. So, given what you currently have, no there isn't a better way of doing this.
2. What do you mean "return all NFTs for an account"? Do you mean when grabbing the transaction? If so, it won't be all NFTs for an account in the meta fields, but rather just those NFTokenPage objects that were shuffled around as a result of the burn. For a low number of NFTs owned by a given account, this will happen to be the same as all of their NFTs, but it should not be if the number of NFTs owned by that account increases beyond 32 (when burning the 33nd token) or about 48 (when burning any token). I might be wrong on my math for the threshold there, but the point is the same :)
