### ISSUE TITLE
Why do xrpl requests sometimes return "unknownCmd" errors? Sometimes it works just fine.

### ISSUE THREAD

**Issue by AtosDev** [XRPLF/xrpl.js#2421]
RippledError: Unknown method.
        at RequestManager.handleResponse (E:\Workspace\Marketplace\node_modules\xrpl\dist\npm\client\RequestManager.js:80:27)
        at Connection.onMessage (E:\Workspace\Marketplace\node_modules\xrpl\dist\npm\client\connection.js:236:37)
        at WebSocket.<anonymous> (E:\Workspace\Marketplace\node_modules\xrpl\dist\npm\client\connection.js:255:53)
        at WebSocket.emit (node:events:513:28)
        at Receiver.receiverOnMessage (E:\Workspace\Marketplace\node_modules\ws\lib\websocket.js:1184:20)
        at Receiver.emit (node:events:513:28)
        at Receiver.dataMessage (E:\Workspace\Marketplace\node_modules\ws\lib\receiver.js:541:14)
        at E:\Workspace\Marketplace\node_modules\ws\lib\receiver.js:492:23
        at E:\Workspace\Marketplace\node_modules\ws\lib\permessage-deflate.js:309:9
        at E:\Workspace\Marketplace\node_modules\ws\lib\permessage-deflate.js:392:7 {
    data: {
        error: 'unknownCmd',
        error_code: 32,
        error_message: 'Unknown method.',
        id: 446,
        request: {
            command: 'nft_info',
            id: 446,
            ledger_index: 'validated',
            nft_id: '000817024B9394C8E019E3E0EEB6540AB2FE4CA7AAFD590768629D7C0000005E'
        },
        status: 'error',
        type: 'response'
    }
}

**Comment by ckniffen** [comment]
This is because s2.ripple.com has both rippled reporting mode and clio servers.  The reporting mode servers are those that are returning `unknownCmd` for you.

**Comment by AtosDev** [comment]
if so, how to solve this problem?

**Comment by AtosDev** [comment]
`nft_info` command is valid, but I'm not sure why it returns `unknownCmd`.
And sometimes it's failed, even though they are same request.

**Comment by JST5000** [comment]
Hey @AtosDev, the `nft_info` command is only valid for clio nodes, so the same request will be processed differently depending on what type of server ends up receiving the request. (Clio nodes support a superset of requests that a rippled node can because they store data in a more searchable format - rippled nodes use the ledger itself which is optimized for minimizing space used & efficiency of handling transactions instead of ability to respond to requests)

If you want to consistently be able to make the `nft_info` request, I'd recommend running your own clio node locally. 

You can follow these instructions here for how to get clio up and running: https://xrpl.org/install-clio-on-ubuntu.html
Or look here for more details on how clio works: https://xrpl.org/the-clio-server.html
Or for a far more in depth explanation of clio, you can see its README here: https://github.com/XRPLF/clio
